[[tests]]
input = '''
1.75 h
'''
output = '''
69.224998
'''

[[tests]]
input = '''
1.60 m
'''
output = '''
54.660000
'''

[[tests]]
input = '''
1.80 h
'''
output = '''
72.859993
'''

[[tests]]
input = '''
1.70 m
'''
output = '''
60.870003
'''

[[tests]]
input = '''
1.50 h
'''
output = '''
51.049999
'''
