[[tests]]
input = '''
3.14159
'''
output = '''
180.000000
'''

[[tests]]
input = '''
1.5708
'''
output = '''
90.000282
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
0.7854
'''
output = '''
45.000141
'''

[[tests]]
input = '''
6.28318
'''
output = '''
360.000000
'''
