[[tests]]
input = '''
3.0 4.0
'''
output = '''
5.00
'''

[[tests]]
input = '''
0.0 0.0
'''
output = '''
0.00
'''

[[tests]]
input = '''
1.0 0.0
'''
output = '''
1.00
'''

[[tests]]
input = '''
5.0 5.0
'''
output = '''
7.07
'''

[[tests]]
input = '''
-3.0 4.0
'''
output = '''
5.00
'''
