[[tests]]
input = '''
5
'''
output = '''
25.000000
2.236068
'''

[[tests]]
input = '''
-3
'''
output = '''
Invalido: numero negativo
'''

[[tests]]
input = '''
0
'''
output = '''
0.000000
0.000000
'''

[[tests]]
input = '''
7
'''
output = '''
49.000000
2.645751
'''

[[tests]]
input = '''
10
'''
output = '''
100.000000
3.162278
'''
