[[tests]]
input = '''
4
'''
output = '''
2.000000
'''

[[tests]]
input = '''
0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
-9
'''
output = '''
81.000000
'''

[[tests]]
input = '''
1
'''
output = '''
1.000000
'''

[[tests]]
input = '''
16
'''
output = '''
4.000000
'''
