[[tests]]
input = '''
0.0
'''
output = '''
32.000000
'''

[[tests]]
input = '''
100.0
'''
output = '''
212.000000
'''

[[tests]]
input = '''
-40.0
'''
output = '''
-40.000000
'''

[[tests]]
input = '''
37.0
'''
output = '''
98.599998
'''

[[tests]]
input = '''
25.0
'''
output = '''
77.000000
'''
