[[tests]]
input = '''
1.0
'''
output = '''
1.610000
'''

[[tests]]
input = '''
10.0
'''
output = '''
16.100000
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
100.0
'''
output = '''
161.000000
'''

[[tests]]
input = '''
5.0
'''
output = '''
8.050000
'''
