[[tests]]
input = '''
32.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
212.0
'''
output = '''
100.000000
'''

[[tests]]
input = '''
-40.0
'''
output = '''
-40.000000
'''

[[tests]]
input = '''
98.6
'''
output = '''
37.000000
'''

[[tests]]
input = '''
77.0
'''
output = '''
25.000000
'''
