[[tests]]
input = '''
10000.0
'''
output = '''
2.470000
'''

[[tests]]
input = '''
1.0
'''
output = '''
0.000247
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
4048.58
'''
output = '''
0.999999
'''

[[tests]]
input = '''
100.0
'''
output = '''
0.024700
'''
