[[tests]]
input = '''
0.0
'''
output = '''
273.149994
'''

[[tests]]
input = '''
100.0
'''
output = '''
373.149994
'''

[[tests]]
input = '''
-273.15
'''
output = '''
0.000006
'''

[[tests]]
input = '''
25.0
'''
output = '''
298.149994
'''

[[tests]]
input = '''
37.0
'''
output = '''
310.149994
'''
