[[tests]]
input = '''
1
'''
output = '''
5
'''

[[tests]]
input = '''
0
'''
output = '''
0
'''

[[tests]]
input = '''
10
'''
output = '''
50
'''

[[tests]]
input = '''
-3
'''
output = '''
-15
'''

[[tests]]
input = '''
5
'''
output = '''
25
'''
