[[tests]]
input = '''
25.0
'''
output = '''
5.000000
'''

[[tests]]
input = '''
10.0
'''
output = '''
2.000000
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
7.5
'''
output = '''
1.500000
'''

[[tests]]
input = '''
100.0
'''
output = '''
20.000000
'''
