[[tests]]
input = '''
1000.0
'''
output = '''
1º Ganhador: R$ 358800.00
2º Ganhador: R$ 249600.00
3º Ganhador: R$ 171600.00
'''

[[tests]]
input = '''
5000.0
'''
output = '''
1º Ganhador: R$ 358800.00
2º Ganhador: R$ 249600.00
3º Ganhador: R$ 171600.00
'''

[[tests]]
input = '''
0.0
'''
output = '''
1º Ganhador: R$ 358800.00
2º Ganhador: R$ 249600.00
3º Ganhador: R$ 171600.00
'''

[[tests]]
input = '''
250.0
'''
output = '''
1º Ganhador: R$ 358800.00
2º Ganhador: R$ 249600.00
3º Ganhador: R$ 171600.00
'''

[[tests]]
input = '''
10000.0
'''
output = '''
1º Ganhador: R$ 358800.00
2º Ganhador: R$ 249600.00
3º Ganhador: R$ 171600.00
'''
