[[tests]]
input = '''
273.15
'''
output = '''
-0.000006
'''

[[tests]]
input = '''
373.15
'''
output = '''
99.999992
'''

[[tests]]
input = '''
0.0
'''
output = '''
-273.149994
'''

[[tests]]
input = '''
300.0
'''
output = '''
26.850000
'''

[[tests]]
input = '''
100.0
'''
output = '''
-173.149994
'''
