[[tests]]
input = '''
1.0
'''
output = '''
0.450000
'''

[[tests]]
input = '''
10.0
'''
output = '''
4.500000
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
2.22
'''
output = '''
0.999000
'''

[[tests]]
input = '''
100.0
'''
output = '''
45.000000
'''
