[[tests]]
input = '''
10 30 0 3600
'''
output = '''
11:30:00
'''

[[tests]]
input = '''
23 59 59 1
'''
output = '''
00:00:00
'''

[[tests]]
input = '''
0 0 0 0
'''
output = '''
00:00:00
'''

[[tests]]
input = '''
12 0 0 7200
'''
output = '''
14:00:00
'''

[[tests]]
input = '''
8 30 45 5000
'''
output = '''
09:54:05
'''
