[[tests]]
input = '''
1.0
'''
output = '''
10000.000000
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
10.0
'''
output = '''
100000.000000
'''

[[tests]]
input = '''
0.5
'''
output = '''
5000.000000
'''

[[tests]]
input = '''
100.0
'''
output = '''
1000000.000000
'''
