[[tests]]
input = '''
100.0 10.0
'''
output = '''
88.00
'''

[[tests]]
input = '''
200.0 5.0
'''
output = '''
176.00
'''

[[tests]]
input = '''
50.0 0.0
'''
output = '''
44.00
'''

[[tests]]
input = '''
0.0 50.0
'''
output = '''
0.00
'''

[[tests]]
input = '''
1000.0 15.0
'''
output = '''
880.00
'''
