[[tests]]
input = '''
120000
'''
output = '''
19900.00
'''

[[tests]]
input = '''
90000
'''
output = '''
13250.00
'''

[[tests]]
input = '''
70000
'''
output = '''
10400.00
'''

[[tests]]
input = '''
50000
'''
output = '''
7550.00
'''

[[tests]]
input = '''
30000
'''
output = '''
4700.00
'''

[[tests]]
input = '''
10000
'''
output = '''
1800.00
'''
