[[tests]]
input = '''
25 2024
'''
output = '''
1999
'''

[[tests]]
input = '''
0 2024
'''
output = '''
2024
'''

[[tests]]
input = '''
30 2000
'''
output = '''
1970
'''

[[tests]]
input = '''
18 2025
'''
output = '''
2007
'''

[[tests]]
input = '''
50 2024
'''
output = '''
1974
'''
