[[tests]]
input = '''
1.0
'''
output = '''
0.910000
'''

[[tests]]
input = '''
10.0
'''
output = '''
9.100000
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
100.0
'''
output = '''
91.000000
'''

[[tests]]
input = '''
5.0
'''
output = '''
4.550000
'''
