[[tests]]
input = '''
1.0
'''
output = '''
1000.000000
'''

[[tests]]
input = '''
0.5
'''
output = '''
500.000000
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
2.5
'''
output = '''
2500.000000
'''

[[tests]]
input = '''
10.0
'''
output = '''
10000.000000
'''
