[[tests]]
input = '''
10.0
'''
output = '''
36.000000
'''

[[tests]]
input = '''
27.78
'''
output = '''
100.008003
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
20.0
'''
output = '''
72.000000
'''

[[tests]]
input = '''
1.0
'''
output = '''
3.600000
'''
