[[tests]]
input = '''
10000.0
'''
output = '''
1.000000
'''

[[tests]]
input = '''
1.0
'''
output = '''
0.000100
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
50000.0
'''
output = '''
5.000000
'''

[[tests]]
input = '''
100.0
'''
output = '''
0.010000
'''
