[[tests]]
input = '''
36.0
'''
output = '''
10.000000
'''

[[tests]]
input = '''
100.0
'''
output = '''
27.777779
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
72.0
'''
output = '''
20.000000
'''

[[tests]]
input = '''
1.0
'''
output = '''
0.277778
'''
