[[tests]]
input = '''
30000.0
'''
output = '''
40500.00
'''

[[tests]]
input = '''
15000.0
'''
output = '''
18750.00
'''

[[tests]]
input = '''
10000.0
'''
output = '''
10500.00
'''

[[tests]]
input = '''
25000.0
'''
output = '''
31250.00
'''

[[tests]]
input = '''
50000.0
'''
output = '''
67500.00
'''
