[[tests]]
input = '''
1.0
'''
output = '''
2.222222
'''

[[tests]]
input = '''
10.0
'''
output = '''
22.222221
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
0.45
'''
output = '''
1.000000
'''

[[tests]]
input = '''
100.0
'''
output = '''
222.222229
'''
