[[tests]]
input = '''
3.0 4.0
'''
output = '''
5.00
'''

[[tests]]
input = '''
5.0 12.0
'''
output = '''
13.00
'''

[[tests]]
input = '''
0.0 0.0
'''
output = '''
0.00
'''

[[tests]]
input = '''
1.0 1.0
'''
output = '''
1.41
'''

[[tests]]
input = '''
8.0 15.0
'''
output = '''
17.00
'''
