[[tests]]
input = '''
180.0
'''
output = '''
3.141590
'''

[[tests]]
input = '''
90.0
'''
output = '''
1.570795
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
45.0
'''
output = '''
0.785398
'''

[[tests]]
input = '''
360.0
'''
output = '''
6.283180
'''
