[[tests]]
input = '''
3.0
'''
output = '''
9.000000
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
-2.0
'''
output = '''
4.000000
'''

[[tests]]
input = '''
10.5
'''
output = '''
110.250000
'''

[[tests]]
input = '''
1.0
'''
output = '''
1.000000
'''
