[[tests]]
input = '''
3661
'''
output = '''
1:01:01
'''

[[tests]]
input = '''
7200
'''
output = '''
2:00:00
'''

[[tests]]
input = '''
0
'''
output = '''
0:00:00
'''

[[tests]]
input = '''
86399
'''
output = '''
23:05:59
'''

[[tests]]
input = '''
3600
'''
output = '''
1:00:00
'''
