[[tests]]
input = '''
1.61
'''
output = '''
1.000000
'''

[[tests]]
input = '''
10.0
'''
output = '''
6.211180
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
100.0
'''
output = '''
62.111801
'''

[[tests]]
input = '''
5.0
'''
output = '''
3.105590
'''
