[[tests]]
input = '''
1.0
'''
output = '''
3.141592
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
5.0
'''
output = '''
78.539803
'''

[[tests]]
input = '''
10.0
'''
output = '''
314.159210
'''

[[tests]]
input = '''
2.5
'''
output = '''
19.634951
'''
