[[tests]]
input = '''
1.0
'''
output = '''
4048.580078
'''

[[tests]]
input = '''
0.0
'''
output = '''
0.000000
'''

[[tests]]
input = '''
10.0
'''
output = '''
40485.800781
'''

[[tests]]
input = '''
0.000247
'''
output = '''
0.999999
'''

[[tests]]
input = '''
100.0
'''
output = '''
404858.000000
'''
